### PR TITLE
(Enhancement) Adding CLI Banner with cfonts

### PR DESCRIPTION
**Pull request by xyizko**
# What ?

1. Adding a banner to the cli using [`https://lib.rs/crates/cfonts`](https://lib.rs/crates/cfonts)
2. Color is based on the text displayed with `soldeer version`

# AIUse 

1. Minimal to determine location of function without interfering with main logic 

# IMG
xjpg

### CODE REVIEW

**Comment by mario-eth** [comment]
Hey, thank you for the PR. We need to see if we can merge this one as it might make the terminal a bit too crowded especially if you use foundry

**Comment by xyizko** [comment]
> Hey, thank you for the PR. We need to see if we can merge this one as it might make the terminal a bit too crowded especially if you use foundry

Yes I can see that. Maybe I can make it smaller ?

**Comment by mario-eth** [comment]
We can try yes but it will probably merged in 0.4.0 so better try to do the pr against the 0.4.0 branch

**Comment by xyizko** [comment]
↗️  Deferred to -  https://github.com/mario-eth/soldeer/pull/199

**Pull request closed without merging**
